### PR TITLE
Python 2/3 support

### PR DESCRIPTION
**Pull request by kotfic**

### CODE REVIEW

**Comment by kotfic** [comment]
I am still having some trouble getting python-mapnik to compile locally to do some integration testing for the python 3 changes. Once i'm convinced the examples etc work then i'll be looking for review.

**Comment by kotfic** [comment]
@dorukozturk @danlamanna  PTAL  -  can you run stuff in the ```example/``` folder and try this with the integration tests in geonotebook? thanks!

**Comment by aashish24** [comment]
@kotfic @dorukozturk is out at the moment. If not @danlamanna is not available perhaps @danlipsa can run the tests.

**Comment by kotfic** [comment]
I found the following workflow to be helpful for getting python's mapnik installed under python 3:

```sh
# install system mapnik v3.0.13 (e.g. pacman -S mapnik)
# assumes you're in a virtualenv or whatevre

git clone https://github.com/mapnik/python-mapnik.git
git checkout v3.0.x
pip install wheel
python setup.py bdist_wheel

# compile compile compile

# your mapnik*.whl may have a different name
pip install dist/mapnik-0.1-cp36-cp36m-linux_x86_64.whl
```

You can then install that whl inside other virtualenvs (e.g geonotebook virtualenv)

**Review by dorukozturk — DISMISSED** [review]

**Comment by dorukozturk** [comment]
Examples are working.

However when I try the quickstart example by doing:
```
python /scripts/tilestache-server.py
```

I get 
```
Traceback (most recent call last):
  File "/home/dorukozturk/Envs/python3_ktile/lib/python3.6/site-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/home/dorukozturk/Envs/python3_ktile/lib/python3.6/site-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/home/dorukozturk/projects/ktile/TileStache/__init__.py", line 400, in __call__
    status_code, headers, content = requestHandler2(self.config, path_info, query_string, script_name)
  File "/home/dorukozturk/projects/ktile/TileStache/__init__.py", line 273, in requestHandler2
    status_code, headers, content = layer.getTileResponse(coord, extension)
  File "/home/dorukozturk/projects/ktile/TileStache/Core.py", line 424, in getTileResponse
    tile = self.render(coord, format)
  File "/home/dorukozturk/projects/ktile/TileStache/Core.py", line 530, in render
    tile = apply_palette(tile, self.bitmap_palette, t_index)
  File "/home/dorukozturk/projects/ktile/TileStache/Pixels.py", line 101, in apply_palette
    mapping[(r, g, b)] = pack('!B', palette_color(r, g, b, palette, t_index))
  File "/home/dorukozturk/projects/ktile/TileStache/Pixels.py", line 76, in palette_color
    return distances.index(min(distances))
AttributeError: 'map' object has no attribute 'index'
```

**Comment by aashish24** [comment]
@kotfic looks like this is ready to be merged. Should we?

**Pull request closed without merging**
